server:
  port: 8086
spring:
  #通用的数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_housekeeping?useUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource # 数据池
    hikari:
      # 池中维护的最小连接数
      minimum-idle: 10
      # 池中最大连接数，包括闲置和使用的连接数
      maxmum-pool-size: 20
      # 池中连接最长生命周期，默认为30分钟
      max-lifetime: 1800000
      # 允许最长空闲时间
      idle-timeout: 30000
      # 数据库连接超时时间，默认为30秒
      connection-timeout: 30000

#整合mybatis
mybatis:
  #加载实体类
  type-aliases-package: com.zjz.housekeeping
  #映射文件
  mapper-locations: mapper/*Mapper.xml
  #输出日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

